### ISSUE TITLE
Error: ChatGPT failed to refresh auth token: 403 forbidden

### ISSUE THREAD

**Issue by yagoquesada** [MisterJimson/chatgpt_api_dart#2]
Hey, I am getting a 403 error, someone knows why?

**Comment by MisterJimson** [comment]
OpenAI has made changes since this repo was created with additional reverse engineering prevention tactics.

I would suggest using their newer chat GPT API instead of this going forward.

https://platform.openai.com/docs/guides/chat

**Comment by yagoquesada** [comment]
OK, thank you! 

I've already used the new chat GPT API, and it works fine, the main issue is that I can't refer to prior messages, if I try to maintain a chat conversation it has no memory. I don't know if it's possible with this API, and I have to change something in my flutter app. If you know the answer I would appreciate it, if not it's fine. Thank you anyway!
